GET http://localhost:8080
###
GET http://localhost:8080/types/INFJ
###

GET  https://api.adzuna.com/v1/api/jobs/us/search/2?app_id=a74cad39&app_key=553a2357dcce6aae9d4b2bd6cbb99884&results_per_page=10&what_or=software%20engineer&sort_by=relevance&full_time=1&permanent=1
###

POST http://localhost:8080/jobs/search HTTP/1.1
Content-Type: application/json

{
    "career": "software engineer"
}
